// ─── RUNNING ─────────────────────────────────────────────────────────────
export const running = {
  pageTitle: "Running & Triathlon — the wombat notebook",
  hero: {
    eyebrow: "Running & triathlon",
    headlineLines: ["A logbook of", "finish lines", "(and the suffering"],
    headlineEm: "in between",
    headlineEnd: ").",
    intro:
      "I started running in 2019 because my back hurt from sitting. I haven't really stopped since. Triathlon snuck up on me three years later via a borrowed road bike and a bad decision in the bar after work.",
    image: { src: "/wombat-running.png", alt: "Wombat running" },
  },
  stats: [
    { label: "Career", num: "14,260", unit: "km", sub: "since the first 5k in 2019" },
    { label: "This year", num: "1,612", unit: "km", sub: "on track for a 4,000 km year" },
    { label: "Races", num: "37", sub: "28 run · 7 tri · 2 ultra" },
    { label: "Highest streak", num: "142", unit: "days", sub: "summer 2024, knee finally said no" },
  ],
  prs: {
    title: "Personal bests.",
    meta: "★ = current PR · updated after each race",
    items: [
      { dist: "5k", time: "19:42", pace: "3:56 /km", race: "Vienna Park Run · Aug '24", tri: false },
      { dist: "10k", time: "41:28", pace: "4:09 /km", race: "Linz Stadtlauf · May '25", tri: false },
      { dist: "21.1k", time: "1:32:48", pace: "4:24 /km", race: "Linz Half · Apr '26", tri: false },
      { dist: "42.2k", time: "3:19:14", pace: "4:43 /km", race: "Berlin Marathon · Sep '25", tri: false },
      { dist: "Sprint Tri", time: "1:08:42", pace: "750 · 20 · 5", race: "Klagenfurt · Jul '25", tri: true },
      { dist: "Olympic", time: "2:18:31", pace: "1.5 · 40 · 10", race: "Wiener Neustadt · Aug '25", tri: true },
    ],
  },
  // Race log: filter chips (year + Run/Tri/Ultra) are derived from `rows`
  // below — append a new row and a chip for that year appears automatically.
  // `kindTone` drives both the row pill color and the kind chip ("sky" → Tri,
  // "rose" → Ultra, anything else → Run).
  raceLog: {
    eyebrow: "Race log",
    title: "Every race I've started.",
    rows: [
      {
        date: "Apr 27 '26",
        race: "Linz Half Marathon",
        sub: "Linz, AT · 8°C, light wind",
        kind: "Half",
        kindTone: "default",
        time: "1:32:48",
        pace: "4:24",
        place: "218 / 4 213",
        pinned: true,
        pr: true,
      },
      {
        date: "Mar 02 '26",
        race: "Salzburg Frühlingslauf",
        sub: "Salzburg, AT",
        kind: "10k",
        kindTone: "default",
        time: "42:14",
        pace: "4:13",
        place: "94 / 1 802",
      },
      {
        date: "Sep 28 '25",
        race: "Berlin Marathon",
        sub: "Berlin, DE · sub-3:20 attempt",
        kind: "Full",
        kindTone: "default",
        time: "3:19:14",
        pace: "4:43",
        place: "3 412 / 54k",
        pr: true,
      },
      {
        date: "Aug 17 '25",
        race: "Wiener Neustadt Triathlon",
        sub: "Olympic distance · windy bike leg",
        kind: "Tri",
        kindTone: "sky",
        time: "2:18:31",
        pace: "—",
        place: "42 / 410",
      },
      {
        date: "Jul 06 '25",
        race: "Klagenfurt Sprint Triathlon",
        sub: "First time under 1:10",
        kind: "Tri",
        kindTone: "sky",
        time: "1:08:42",
        pace: "—",
        place: "88 / 612",
      },
      {
        date: "May 11 '25",
        race: "Linz Stadtlauf 10k",
        sub: "Cool morning, perfect day",
        kind: "10k",
        kindTone: "default",
        time: "41:28",
        pace: "4:09",
        place: "42 / 2 184",
      },
      {
        date: "Mar 23 '25",
        race: "Wiener Trail 50",
        sub: "First ultra · don't recommend learning here",
        kind: "Ultra",
        kindTone: "rose",
        time: "6:24:08",
        pace: "7:38",
        place: "112 / 480",
      },
    ],
    footLink: "Show 31 more races →",
  },
  photos: {
    eyebrow: "From the road",
    title: "Photos from races.",
    meta: "Drop in your own snaps — placeholders for now",
    items: [
      {
        size: "big",
        gradient: "linear-gradient(135deg, #C99B5B 0%, #8C6328 70%)",
        tag: "Berlin · 38k mark",
        capTitle: "\"That look.\"",
        capBody:
          "Mile 24 of Berlin. I'd just realized I might actually make sub-3:20. Bricked the last 4km but kept it together.",
      },
      {
        size: "default",
        gradient: "linear-gradient(155deg, #7BB0C8, #486593)",
        tag: "Klagenfurt swim start",
      },
      {
        size: "default",
        gradient: "linear-gradient(135deg, #F0CC6E, #C99B5B)",
        tag: "Linz finish chute",
      },
      {
        size: "default",
        gradient: "linear-gradient(165deg, #E8B5A8, #B5786A)",
        tag: "Trail 50 · aid station",
      },
      {
        size: "default",
        gradient: "linear-gradient(135deg, #6B5640, #3D2E20)",
        tag: "Pre-dawn long run",
      },
      {
        size: "wide",
        gradient: "linear-gradient(135deg, #9BB7A6, #4F6334)",
        tag: "Wienerwald, autumn '25",
        capTitle: "Sunday long run, week 14.",
        capBody:
          "32k loop through the Vienna woods. Best part of every block — the run you don't need to think about, only finish.",
      },
    ],
  },
  upcoming: {
    title: "What's next on the calendar.",
    meta: "3 races on the books",
    items: [
      {
        whenLines: ["04 — 19", "Apr"],
        countdown: "in 47 days",
        countdownAccent: true,
        title: "Vienna City Marathon",
        body: "Goal: 3:15. Currently in week 7 of a 16-week Pfitzinger 18/55 block.",
        tags: [{ label: "Full", tone: "default" }, { label: "Goal race", tone: "default" }],
      },
      {
        whenLines: ["06 — 14", "Jun"],
        countdown: "in 103 days",
        countdownAccent: false,
        title: "Ironman 70.3 Pula",
        body: "First half-Ironman. Big jump from sprint. Bike volume is officially the new hobby.",
        tags: [{ label: "Tri", tone: "sky" }, { label: "70.3", tone: "default" }],
      },
      {
        whenLines: ["09 — 06", "Sep"],
        countdown: "in 187 days",
        countdownAccent: false,
        title: "UTMB CCC 100k",
        titleEm: "(waitlist)",
        body: "The big \"if I get in\" race. Mostly waiting and pretending I'm not.",
        tags: [{ label: "Ultra", tone: "rose" }, { label: "Mountains", tone: "default" }],
      },
    ],
  },
};
